<body class="fullbleed vertical layout">
<paper-drawer-panel class="flex" force-narrow>
    <paper-header-panel drawer>
        <paper-toolbar>
            <div>{{ .Site.Title }}</div>
        </paper-toolbar>
        <div>Coming Soon.</div>
    </paper-header-panel>
    <paper-header-panel main>
        <paper-toolbar>
            <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
        </paper-toolbar>
