<body class="fullbleed vertical layout">
<paper-drawer-panel class="flex" force-narrow>
    <paper-header-panel drawer>
        <paper-toolbar>
            <div>{{ .Site.Title }}</div>
        </paper-toolbar>
        <style>
            paper-header-panel a {
                display: block;
                line-height: 40px;
                background-color: transparent;
                border: none;
                font-size: 14px;
                margin: 20px;
            }
        </style>
        <a tabindex="0" href="/">Home</a>
    </paper-header-panel>
    <paper-header-panel main>
        <paper-toolbar>
            <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
        </paper-toolbar>
