branches:
  only: 
    - master

addons:
  apt:
    packages:
    - python-docutils
    - git

sudo: required

services:
  - docker

before_install:
- openssl aes-256-cbc -K $encrypted_1fa1ae5fd8c9_key -iv $encrypted_1fa1ae5fd8c9_iv
  -in .gcloud.json.enc -out .gcloud.json -d

install:
    sudo ./build/install-dependencies.sh
    make auth
    make build-container-nginx
    make push-container-nginx

before_script:

script:

after_sucess:

after_failure:

after_script:
