branches:
  only: 
    - master

addons:
  apt:
    packages:
    - python-docutils
    - git

sudo: required

services:
  - docker

env:
  - CLOUDSDK_PYTHON_SITEPACKAGES=1

before_install:
- openssl aes-256-cbc -K $encrypted_1fa1ae5fd8c9_key -iv $encrypted_1fa1ae5fd8c9_iv
  -in .gcloud.json.enc -out .gcloud.json -d

install:
  ./build/scripts/CI/install-dependencies.sh

before_script:
  ./build/scripts/CI/auth.sh

script:
  - make deploy-container-nginx
    make deploy

after_sucess:

after_failure:

after_script:
