baseurl: https://docs.littleman.co/
languageCode: en-us

title: Documentation
theme: blackburn

buildDrafts: true

social:
  twitter: andrewhowdencom
  facebook: andrewhowdencom
  github: andrewhowdencom

menu:
  main:
    - Name: "andrewhowden.com"
      URL: "https://andrewhowden.com"

copyright: "© Andrew Howden, 2016"
